export type Bearing = {
  slug: string;
  name: string;
  sku: string;
  gost?: string;
  iso?: string;
  aliases: string[];
  brand?: string;
  type: string;
  d?: number;
  D?: number;
  B?: number;
  massKg?: number;
  clearance?: string;
  precisionClass?: string;
  seals?: string;
  cage?: string;
  ringMaterial?: string;
  rollingElementMaterial?: string;
  temperatureMinC?: number;
  temperatureMaxC?: number;
  dynamicLoadKn?: number;
  staticLoadKn?: number;
  limitingSpeedRpm?: number;
  supplyStatus?: "ON_REQUEST" | "CHECK_AVAILABILITY" | "EXPECTED" | "DISCONTINUED" | "UNKNOWN";
  note?: string;
};
