
-- ----------------------------
-- Table structure for account_codes
-- ----------------------------
DROP TABLE IF EXISTS "public"."account_codes";
CREATE TABLE "public"."account_codes" (
  "code" varchar(4) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
  "name" text COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text
)
;

-- ----------------------------
-- Records of account_codes
-- ----------------------------
INSERT INTO "public"."account_codes" VALUES ('1170', 'Финансовые вложения');
INSERT INTO "public"."account_codes" VALUES ('6326', 'Прочие');
INSERT INTO "public"."account_codes" VALUES ('6350', 'Прочие');
INSERT INTO "public"."account_codes" VALUES ('2220', 'Управленческие расходы');
INSERT INTO "public"."account_codes" VALUES ('2310', 'Доходы от участия в других организациях');
INSERT INTO "public"."account_codes" VALUES ('3100', 'Величина капитала на 31 декабря года, предшествующего предыдущему');
INSERT INTO "public"."account_codes" VALUES ('1140', 'Материальные поисковые активы');
INSERT INTO "public"."account_codes" VALUES ('1260', 'Прочие оборотные активы');
INSERT INTO "public"."account_codes" VALUES ('1320', 'Собственные акции, выкупленные у акционеров');
INSERT INTO "public"."account_codes" VALUES ('1340', 'Переоценка внеоборотных активов');
INSERT INTO "public"."account_codes" VALUES ('1350', 'Добавочный капитал (без переоценки)');
INSERT INTO "public"."account_codes" VALUES ('1400', 'Итого долгосрочных обязательств');
INSERT INTO "public"."account_codes" VALUES ('1530', 'Доходы будущих периодов');
INSERT INTO "public"."account_codes" VALUES ('2100', 'Валовая прибыль (убыток)');
INSERT INTO "public"."account_codes" VALUES ('2411', 'Текущий налог на прибыль');
INSERT INTO "public"."account_codes" VALUES ('2412', 'Отложенный налог на прибыль');
INSERT INTO "public"."account_codes" VALUES ('2430', 'Изменение отложенных налоговых обязательств');
INSERT INTO "public"."account_codes" VALUES ('4219', 'Прочие поступления');
INSERT INTO "public"."account_codes" VALUES ('3311', 'Чистая прибыль, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3221', 'Убыток, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3220', 'Уменьшение капитала - всего, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3214', 'Дополнительный выпуск акций, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3211', 'Чистая прибыль, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('4119', 'Прочие поступления');
INSERT INTO "public"."account_codes" VALUES ('4120', 'Платежи - всего');
INSERT INTO "public"."account_codes" VALUES ('4122', 'В связи с оплатой труда работников');
INSERT INTO "public"."account_codes" VALUES ('4212', 'От продажи акций других организаций (долей участия)');
INSERT INTO "public"."account_codes" VALUES ('4123', 'Проценты по долговым обязательствам');
INSERT INTO "public"."account_codes" VALUES ('4124', 'Налога на прибыль организаций');
INSERT INTO "public"."account_codes" VALUES ('4129', 'Прочие платежи');
INSERT INTO "public"."account_codes" VALUES ('4210', 'Поступления - всего');
INSERT INTO "public"."account_codes" VALUES ('4329', 'Прочие платежи');
INSERT INTO "public"."account_codes" VALUES ('4300', 'Сальдо денежных потоков от финансовых операций');
INSERT INTO "public"."account_codes" VALUES ('6250', 'Прочие');
INSERT INTO "public"."account_codes" VALUES ('3322', 'Переоценка имущества, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3312', 'Переоценка имущества, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3327', 'Дивиденды, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3325', 'Уменьшение количества акций, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3310', 'Увеличение капитала - всего, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('1130', 'Нематериальные поисковые активы');
INSERT INTO "public"."account_codes" VALUES ('4110', 'Поступления - всего');
INSERT INTO "public"."account_codes" VALUES ('3400', 'Капитал всего до корректировок');
INSERT INTO "public"."account_codes" VALUES ('3401', 'Нераспределенная прибыль (непокрытый убыток) до корректировок');
INSERT INTO "public"."account_codes" VALUES ('4113', 'От перепродажи финансовых вложений');
INSERT INTO "public"."account_codes" VALUES ('3600', 'Чистые активы');
INSERT INTO "public"."account_codes" VALUES ('4321', 'Собственникам (участникам) в связи с выкупом у них акций (долей участия) организации или их выходом из состава участников');
INSERT INTO "public"."account_codes" VALUES ('6325', 'Ремонт основных средств и иного имущества');
INSERT INTO "public"."account_codes" VALUES ('3300', 'Величина капитала на 31 декабря отчетного года');
INSERT INTO "public"."account_codes" VALUES ('3200', 'Величина капитала на 31 декабря предыдущего года');
INSERT INTO "public"."account_codes" VALUES ('1360', 'Резервный капитал');
INSERT INTO "public"."account_codes" VALUES ('6100', 'Остаток средств на начало отчетного года');
INSERT INTO "public"."account_codes" VALUES ('6210', 'Вступительные взносы');
INSERT INTO "public"."account_codes" VALUES ('6230', 'Добровольные имущественные взносы и пожертвования');
INSERT INTO "public"."account_codes" VALUES ('6240', 'Прибыль от предпринимательской деятельности организации');
INSERT INTO "public"."account_codes" VALUES ('6312', 'Проведение конференций, совещаний, семинаров и т. п.');
INSERT INTO "public"."account_codes" VALUES ('6321', 'Расходы, связанные с оплатой труда (включая начисления)');
INSERT INTO "public"."account_codes" VALUES ('6324', 'Содержание помещений, зданий, автомобильного транспорта и иного имущества (кроме ремонта)');
INSERT INTO "public"."account_codes" VALUES ('6330', 'Приобретение основных средств, инвентаря и иного имущества');
INSERT INTO "public"."account_codes" VALUES ('6400', 'Остаток средств на конец отчетного года');
INSERT INTO "public"."account_codes" VALUES ('3224', 'Уменьшение номинальной стоимости акций, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3212', 'Переоценка имущества, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3223', 'Расходы, относящиеся непосредственно на уменьшение капитала, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3216', 'Реорганизация юридического лица, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3240', 'Изменение резервного капитала, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3215', 'Увеличение номинальной стоимости акций, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3230', 'Изменение добавочного капитала, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3226', 'Реорганизация юридического лица, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3225', 'Уменьшение количества акций, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3326', 'Реорганизация юридического лица, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3330', 'Изменение добавочного капитала, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3320', 'Уменьшение капитала - всего, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3316', 'Реорганизация юридического лица, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3315', 'Увеличение номинальной стоимости акций, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3402', 'Другие статьи капитала, по которым осуществлены корректировки до корректировок');
INSERT INTO "public"."account_codes" VALUES ('3502', 'Другие статьи капитала, по которым осуществлены корректировки после корректировок');
INSERT INTO "public"."account_codes" VALUES ('3210', 'Увеличение капитала - всего, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('2500', 'Совокупный финансовый результат периода');
INSERT INTO "public"."account_codes" VALUES ('6311', 'Социальная и благотворительная помощь');
INSERT INTO "public"."account_codes" VALUES ('3313', 'Доходы, относящиеся непосредственно на увеличение капитала, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3500', 'Капитал - всего после корректировок');
INSERT INTO "public"."account_codes" VALUES ('3411', 'Корректировка в связи с изменением учетной политики');
INSERT INTO "public"."account_codes" VALUES ('3501', 'Нераспределенная прибыль (непокрытый убыток) после корректировок');
INSERT INTO "public"."account_codes" VALUES ('3227', 'Дивиденды, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3222', 'Переоценка имущества, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('3323', 'Расходы, относящиеся непосредственно на уменьшение капитала, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3324', 'Уменьшение номинальной стоимости акций, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3321', 'Убыток, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3314', 'Дополнительный выпуск акций, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('3213', 'Доходы, относящиеся непосредственно на увеличение капитала, за предыдущий год');
INSERT INTO "public"."account_codes" VALUES ('1110', 'Нематериальные активы');
INSERT INTO "public"."account_codes" VALUES ('1410', 'Долгосрочные заемные средства');
INSERT INTO "public"."account_codes" VALUES ('3412', 'Корректировка в связи с изменением учетной политики');
INSERT INTO "public"."account_codes" VALUES ('3422', 'Корректировка в связи с исправлением ошибок');
INSERT INTO "public"."account_codes" VALUES ('1700', 'Баланс (пассив)');
INSERT INTO "public"."account_codes" VALUES ('2110', 'Выручка');
INSERT INTO "public"."account_codes" VALUES ('2120', 'Себестоимость продаж');
INSERT INTO "public"."account_codes" VALUES ('2330', 'Проценты к уплате');
INSERT INTO "public"."account_codes" VALUES ('2410', 'Налог на прибыль');
INSERT INTO "public"."account_codes" VALUES ('2400', 'Чистая прибыль (убыток)');
INSERT INTO "public"."account_codes" VALUES ('3410', 'Корректировка в связи с изменением учетной политики');
INSERT INTO "public"."account_codes" VALUES ('3420', 'Корректировка в связи с исправлением ошибок');
INSERT INTO "public"."account_codes" VALUES ('3421', 'Корректировка в связи с исправлением ошибок');
INSERT INTO "public"."account_codes" VALUES ('3340', 'Изменение резервного капитала, за отчетный год');
INSERT INTO "public"."account_codes" VALUES ('1160', 'Доходные вложения в материальные ценности');
INSERT INTO "public"."account_codes" VALUES ('2450', 'Изменение отложенных налоговых активов');
INSERT INTO "public"."account_codes" VALUES ('4312', 'Денежных вкладов собственников (участников)');
INSERT INTO "public"."account_codes" VALUES ('2340', 'Прочие доходы');
INSERT INTO "public"."account_codes" VALUES ('2350', 'Прочие расходы');
INSERT INTO "public"."account_codes" VALUES ('2530', 'Налог на прибыль от операций, результат которых не включается в чистую прибыль (убыток) периода');
INSERT INTO "public"."account_codes" VALUES ('2210', 'Коммерческие расходы');
INSERT INTO "public"."account_codes" VALUES ('2200', 'Прибыль (убыток) от продаж');
INSERT INTO "public"."account_codes" VALUES ('2320', 'Проценты к получению');
INSERT INTO "public"."account_codes" VALUES ('2300', 'Прибыль (убыток) до налогообложения');
INSERT INTO "public"."account_codes" VALUES ('2421', 'Постоянные налоговые обязательства');
INSERT INTO "public"."account_codes" VALUES ('2510', 'Результат от переоценки внеоборотных активов, не включаемый в чистую прибыль (убыток) периода');
INSERT INTO "public"."account_codes" VALUES ('2520', 'Результат от прочих операций, не включаемый в чистую прибыль (убыток) периода');
INSERT INTO "public"."account_codes" VALUES ('4211', 'От продажи внеоборотных активов (кроме финансовых вложений)');
INSERT INTO "public"."account_codes" VALUES ('4220', 'Платежи - всего');
INSERT INTO "public"."account_codes" VALUES ('4310', 'Поступления - всего');
INSERT INTO "public"."account_codes" VALUES ('1150', 'Основные средства');
INSERT INTO "public"."account_codes" VALUES ('6215', 'Членские взносы');
INSERT INTO "public"."account_codes" VALUES ('6220', 'Целевые взносы');
INSERT INTO "public"."account_codes" VALUES ('6200', 'Поступило средств - всего');
INSERT INTO "public"."account_codes" VALUES ('6310', 'Расходы на целевые мероприятия');
INSERT INTO "public"."account_codes" VALUES ('6313', 'Иные мероприятия');
INSERT INTO "public"."account_codes" VALUES ('6320', 'Расходы на содержание аппарата управления');
INSERT INTO "public"."account_codes" VALUES ('6322', 'Выплаты, не связанные с оплатой труда');
INSERT INTO "public"."account_codes" VALUES ('6323', 'Расходы на служебные командировки и деловые поездки');
INSERT INTO "public"."account_codes" VALUES ('6300', 'Использовано средств - всего');
INSERT INTO "public"."account_codes" VALUES ('1120', 'Результаты исследований и разработок');
INSERT INTO "public"."account_codes" VALUES ('1190', 'Прочие внеоборотные активы');
INSERT INTO "public"."account_codes" VALUES ('1100', 'Итого внеоборотных активов');
INSERT INTO "public"."account_codes" VALUES ('1230', 'Дебиторская задолженность');
INSERT INTO "public"."account_codes" VALUES ('1600', 'Баланс (актив)');
INSERT INTO "public"."account_codes" VALUES ('1510', 'Краткосрочные заемные обязательства');
INSERT INTO "public"."account_codes" VALUES ('1200', 'Итого оборотных активов');
INSERT INTO "public"."account_codes" VALUES ('1520', 'Краткосрочная кредиторская задолженность');
INSERT INTO "public"."account_codes" VALUES ('1310', 'Уставный капитал (складочный капитал, уставный фонд, вклады товарищей)');
INSERT INTO "public"."account_codes" VALUES ('1370', 'Нераспределенная прибыль (непокрытый убыток)');
INSERT INTO "public"."account_codes" VALUES ('1550', 'Прочие краткосрочные обязательства');
INSERT INTO "public"."account_codes" VALUES ('1420', 'Отложенные налоговые обязательства');
INSERT INTO "public"."account_codes" VALUES ('1430', 'Оценочные обязательства');
INSERT INTO "public"."account_codes" VALUES ('1250', 'Денежные средства и денежные эквиваленты');
INSERT INTO "public"."account_codes" VALUES ('1540', 'Оценочные обязательства');
INSERT INTO "public"."account_codes" VALUES ('1500', 'Итого краткосрочных обязательств');
INSERT INTO "public"."account_codes" VALUES ('1210', 'Запасы');
INSERT INTO "public"."account_codes" VALUES ('1240', 'Финансовые вложения (за исключением денежных эквивалентов)');
INSERT INTO "public"."account_codes" VALUES ('1300', 'Итого капитал');
INSERT INTO "public"."account_codes" VALUES ('1450', 'Прочие долгосрочные обязательства');
INSERT INTO "public"."account_codes" VALUES ('2910', 'Разводненная прибыль (убыток) на акцию');
INSERT INTO "public"."account_codes" VALUES ('2900', 'Базовая прибыль (убыток) на акцию');
INSERT INTO "public"."account_codes" VALUES ('1180', 'Отложенные налоговые активы');
INSERT INTO "public"."account_codes" VALUES ('1220', 'Налог на добавленную стоимость по приобретенным ценностям');
INSERT INTO "public"."account_codes" VALUES ('2460', 'Прочее');
INSERT INTO "public"."account_codes" VALUES ('4111', 'От продажи продукции, товаров, работ и услуг');
INSERT INTO "public"."account_codes" VALUES ('4112', 'Арендных платежей, лицензионных платежей, роялти, комиссионных и иных аналогичных платежей');
INSERT INTO "public"."account_codes" VALUES ('4121', 'Поставщикам (подрядчикам) за сырье, материалы, работы, услуги');
INSERT INTO "public"."account_codes" VALUES ('4100', 'Сальдо денежных потоков от текущих операций');
INSERT INTO "public"."account_codes" VALUES ('4214', 'Дивидендов, процентов по долговым финансовым вложениям и аналогичных поступлений от долевого участия в других организациях');
INSERT INTO "public"."account_codes" VALUES ('4222', 'В связи с приобретением акций других организаций (долей участия)');
INSERT INTO "public"."account_codes" VALUES ('4224', 'Процентов по долговым обязательствам, включаемым в стоимость инвестиционного актива');
INSERT INTO "public"."account_codes" VALUES ('4229', 'Прочие платежи');
INSERT INTO "public"."account_codes" VALUES ('4200', 'Сальдо денежных потоков от инвестиционных операций');
INSERT INTO "public"."account_codes" VALUES ('4311', 'Получение кредитов и займов');
INSERT INTO "public"."account_codes" VALUES ('4313', 'От выпуска акций, увеличения долей участия');
INSERT INTO "public"."account_codes" VALUES ('4314', 'От выпуска облигаций, векселей и других долговых ценных бумаг и др.');
INSERT INTO "public"."account_codes" VALUES ('4319', 'Прочие поступления');
INSERT INTO "public"."account_codes" VALUES ('4320', 'Платежи - всего');
INSERT INTO "public"."account_codes" VALUES ('4322', 'На уплату дивидендов и иных платежей по распределению прибыли в пользу собственников (участников)');
INSERT INTO "public"."account_codes" VALUES ('4323', 'В связи с погашением (выкупом) векселей и других долговых ценных бумаг, возврат кредитов и займов');
INSERT INTO "public"."account_codes" VALUES ('4400', 'Сальдо денежных потоков за отчетный период');
INSERT INTO "public"."account_codes" VALUES ('4450', 'Остаток денежных средств и денежных эквивалентов на начало отчетного периода');
INSERT INTO "public"."account_codes" VALUES ('4500', 'Остаток денежных средств и денежных эквивалентов на конец отчетного периода');
INSERT INTO "public"."account_codes" VALUES ('4213', 'От возврата предоставленных займов, от продажи долговых ценных бумаг (прав требования денежных средств к другим лицам)');
INSERT INTO "public"."account_codes" VALUES ('4221', 'В связи с приобретением, созданием, модернизацией, реконструкцией и подготовкой к использованию внеоборотных активов');
INSERT INTO "public"."account_codes" VALUES ('4223', 'В связи с приобретением долговых ценных бумаг (прав требования денежных средств к другим лицам), предоставление займов другим лицам');
INSERT INTO "public"."account_codes" VALUES ('4490', 'Величина влияния изменений курса иностранной валюты по отношению к рублю');

-- ----------------------------
-- Primary Key structure for table account_codes
-- ----------------------------
ALTER TABLE "public"."account_codes" ADD CONSTRAINT "account_codes_pkey" PRIMARY KEY ("code");
